apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoibWF5Zmxvd3dlciIsInBhc3N3b3JkIjoiUGFyYWIwbEAiLCJlbWFpbCI6Im1heWZsb3d3ZXJAZ21haWwuY29tIiwiYXV0aCI6ImJXRjVabXh2ZDNkbGNqcFFZWEpoWWpCc1FBPT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: dockerconfigjson
  namespace: cinemaabyss
type: kubernetes.io/dockerconfigjson