apiVersion: v1
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAidXNlcm5hbWUiOiAibWF5Zmxvd3dlciIsCiAgICAgICJwYXNzd29yZCI6ICJnaHBfWFpwc0hndlk0Z1JLM1p4RkI2ZHBLYTRwS2dGSHE1MjRPeFNrIiwKICAgICAgImVtYWlsIjogIm5vbmUiLAogICAgICAiYXV0aCI6ICJiV0Y1Wm14dmQzZGxjanBuYUhCZldGcHdjMGhuZGxrMFoxSkxNMXA0UmtJMlpIQkxZVFJ3UzJkR1NIRTFNalJQZUZOciIKICAgIH0KICB9Cn0K
kind: Secret
metadata:
  creationTimestamp: null
  name: dockerconfigjson
  namespace: cinemaabyss
type: kubernetes.io/dockerconfigjson